import { Container, Row, Col } from "react-bootstrap";

export default function NewReleases() {
  return (
    <>
      <Container>
        <Row>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
        </Row>
        <Row>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
        </Row>
        <Row>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
        </Row>
        <Row>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
        </Row>
        <Row>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
        </Row>
        <Row>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
        </Row>
        <Row>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
        </Row>
        <Row>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
          <Col>teste</Col>
        </Row>
      </Container>
    </>
  );
}
